name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *" # 18:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          persist-credentials: false

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Reconfigurar a URL do remote com token
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${USERNAME}/${REPO}.git

          git add -A

          # evitar commit vazio
          if git diff --cached --quiet; then
            echo "Sem mudan√ßas para commitar"
            exit 0
          fi

          git commit -m "generated"

          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
